# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Mobile Day Córdoba"
email: "gdgcordoba@gmail.com"
description: "El Mobile Day es un evento que trata de mostrar las diversas teconologías para el desarrollo móvil"
baseurl: "/"
url: "http://gdgcordoba.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Córdoba"
organizerAlternateName: "Google Developer Group Córdoba"
organizerDescription: "Grupo para compartir, discutir y disfrutar de las tecnologías Google en Córdoba (España) desde los ojos de los apasionados de la programación; lo que no significa que seamos solo programadores: cualquier persona que le guste Google y quiera aprender sobre tecnología es bienvenida."
organizerEmail: "gdgcordoba@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgcordoba.com"

# Head
metaKeywords: "event, gdg, mobile, google, programming, android, chrome, developers"
twitterAccount: "@GDGCordobaESP"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Programa"}
 - {permalink: "/speakers/", text: "Ponentes"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Mobile Day <typeout> 2016"
eventDate: "25 de Junio, 2016"
typeoutTextValues: '"", "Córdoba", "Salmorejo", "Córdoba", "Berenjena", "Córdoba", "Ai! que caló"'
typeoutFallback: "Season"


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Rectorado de la UCO"
eventLocationName: "Salón de actos"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Av. Medina Azahara 4"
eventAddressLocality: "Córdoba"
eventAddressLocalityRegion: "Córdoba"
eventPostalCode: "14005"
eventAddressCountry: "España"
eventStartTime: "2016-6-25T10:00"
eventDoorTime: "10:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "37.884626, -4.788775"
mapCenterCoordinates: "37.884626, -4.788775"
mapMobileCenterCoordinates: "37.884626, -4.788775"

# Speakers List Block
showSessions: true

